name: 'project_tesla'
version: '1.0.0'
config-version: 2

profile: 'project_tesla'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  project_tesla:
    staging:
      +materialized: view
    marts:
      +materialized: table

seeds:
  project_tesla:
    tesla_results:
      +column_types:
        year: integer
        price: varchar
        odometer: varchar
      +quote_columns: true
